name = "porahobe-website"
compatibility_date = "2024-11-01"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB"
database_name = "porahobe-db"
database_id = "local-db-id"

# Removed R2 bindings to use S3 (Backblaze B2) instead.
