name = "porahobe-website"
compatibility_date = "2024-11-01"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB"
database_name = "porahobe-db"
database_id = "local-db-id"

[[r2_buckets]]
binding = "R2"
bucket_name = "porahobe-r2"
preview_bucket_name = "porahobe-r2"
